FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 5173
# Thêm -- --host để Vite mở cổng cho Docker kết nối ra ngoài máy thật của bạn
CMD ["npm", "run", "dev", "--", "--host"]
