apiVersion: v1
kind: ConfigMap

metadata:
  name: todo-config
  namespace: todo-app

data:
  NODE_ENV: "production"

  PORT: "5000"

  DB_HOST: "postgesql-postgresql.do2602-hungcm.svc.cluster.local"

  DB_PORT: "5432"

  DB_NAME: "db_todo"
